name: 'Trigger workflow action'
description: 'Trigger workflow in another repository'
branding:
  icon: arrow-right-circle
  color: green
inputs:
  token:
    description: 'personal access token'
    required: true
  repository:
    description: 'repository'
    required: true
  workflowId:
    description: 'ID of workflow'
    required: false
    default: 'build.yml'
  branch:
    description: 'branch'
    required: false
    default: 'main'
runs:
  using: 'composite'
  steps:
    - name: Trigger workflow
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.token }}
        script: |
          const [owner, repo] = core.getInput('repository').split('/');

          await github.actions.createWorkflowDispatch({
            owner: owner,
            repo: repo,
            workflow_id: core.getInput('workflowId'),
            ref: core.getInput('branch')
          });